# Generated by Django 4.1.1 on 2023-01-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, max_length=255)),
                ('flight_name', models.CharField(max_length=255)),
                ('flight_no', models.CharField(max_length=255)),
                ('flight_day', models.CharField(max_length=255)),
                ('flight_date', models.DateTimeField(auto_now_add=True, max_length=255)),
                ('flight_cancellation', models.CharField(max_length=255)),
                ('flight_time', models.CharField(max_length=255)),
                ('select', models.CharField(max_length=255)),
            ],
        ),
    ]
